[package]
name = "lxd"
version = "0.1.0"
authors = ["Daniel Watkins <daniel@daniel-watkins.co.uk>"]

[dependencies]
hyper = "0.6"
url = "0.2"
serde = "*"
serde_json = "*"
serde_macros = "*"
clap = "*"
yaml-rust = "*"
